name: Generate snake animation

on:
  schedule: # Exécute toutes les 12 heures
    - cron: "* */12 * * *"
  workflow_dispatch: # Permet d'exécuter manuellement
  push:
    branches:
      - main # Déclenche l'action sur les commits vers la branche main

jobs:
  generate:
    permissions:
      contents: write # Permet d'écrire dans le dépôt
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: sounyatje # Utilisez votre nom d'utilisateur GitHub
          outputs: dist/snake.svg?palette=github-dark # Définit où l'animation sera générée

      - name: Install ImageMagick
        run: sudo apt-get install imagemagick

      - name: Convert SVG to GIF
        run: convert dist/snake.svg dist/snake.gif # Utilise ImageMagick pour convertir SVG en GIF

      - name: Push snake.svg and snake.gif to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output # Assurez-vous que cette branche existe
          build_dir: dist # Dossier de la génération
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }} # Utilise le token personnalisé que vous avez créé

